sudo: false
language: node_js
node_js:
  - stable
env:
  global:
    - BUILD_TIMEOUT=10000
    - secure: W4CVcF5u8PBynaV4fLqfItZ8f/xnEGcWUtW18BZGyqkYfqCW5colgNmwRdoIIf3L1BZIeB7m6wzJ6uOkQe6Xa9qAT68o0p6ndmEGYx8TGRnEF3EommtuToEf/ERiJgvf76knnH4FFwRrB4pWHicpK/q70tol2hCvI3ltbxls6hsgcZ0soH9KjgONmob0O/q1TJ0ekvKuuTZ/8UYcyFkDmJgOUJ2YOa4eGMDM36Yn4eD2dalaZp9UZBHYkgKVNqIbvpBzOvN34dJLnNM5CzOvsqEHNesDkwfoLoR6cYAPs5s0r89Ks+z7MO5JhvK5Q6B8Z268qOshnz1TO5FISDapQS7w1cVYRCuykrktRM99fBWYTBaEShHjdB/sNngmquWJFfQYvGqiCvVf76oHItMcNH559Hcpo7Eite35mYSNop7wb405WI0w5cMzz+UjyifmGNmLsOe3haazCBnOr57fmj9dHtdaKbeDSV3ahDWVnr5buvCeNoqpBTlfIrzZUwG2Ayw0C1m7xmqy0RmeciFDVvncMUsyRH3XuEGThzIq81GR7HFRWdw4Ufe53nneu9gajPfTLoussC1/oZVY7gOQEvuTqjSsuGKlkmNY3UlsWE7R6NpK/D4YHtZISY8VcTZ3q8bOGx2XWjplkFZNrvGEpOqqMinxBrbiPj5btSYzJFM=
    - secure: PH++vCsmlNy1O+KWuxDzR2BFjEATx/MlO0N6zr0uw7qjKwxkt9M4YHi8rVtz4g4omV6YykAmA5S0VEj99FtwCd9rQM9bPRWxgwQE0cZOXYFJjoNdB8MQs8LHweX9+PqYdL2MWKTmMCdoawvbhnk9JBKhyaOHi9fTbW+rNyG/H/OHVr8dm5O32ctVFWq4OAMOquWYH6T3LZ+dCju3nw6yTGOtKatAAJxyFLPIbtSj6oJ7jSiH16gR49DDXB9a8gSOBsrfmxQtdrPNYCKjbksK0oD01k1U2QuBFpojXbzBi3R9nYsNehtfkXh0wYP4nl+sAA1V2jnsE7iK3oD2WLqrIZVZo/qPiCT04JnG9TL40KUaqz2ymkA+wC2Ed+A72xu9OuoW+CRPqjRYFVe9ZLPz8o4/putstfl0tbOPyibdUDGKU2T1uVisUUf0Ceo5RH/XNkMYh7djbKISxJcD6C5GXc6ruJkFTxvO8OmkoWmYJmPLQnycYeGyzkDIYzi4FI2GGeuc94E/KAfA1+vIIYogj9tDNN4J/MymBIcsk48XbFa4DD9AUoGjk4LvAZIQ9xNe+LhA7tTddU6TblE8GIv0f0dRNbAAAHUgxAJKL8g6J4vLJRWNSlpIplFeAmx2Skh9K3pTsP/Kq9450GnPzvj1BoD+klW6IwOvLBmqclzNGwQ=
    - secure: FIq54UV0peZ16fGEV6CLxccqXrPGZckOui/d3UncO/bLuU1haBJMBeKIoWyTzFhVkBuHp90V2I/7+SVUVMbmYNh9xBww9/iZ+4s+cO5/z4ghlvNscUMPsaBpVHCAZ9cNyNdeLu0mxNZ+/izAD9yqCuWA5NNilWHEIUiJF+oeJslM0Pk8iveDKbkKTCyFCx3cM4/+XTDV9VgqK4lJD9VVL36ZthoUYHhjlRAg7675JnUITPCJTXzuhjr0w/sPT07Q/iqD3LisZNqXsP1j2BP9sqLSbZfm65P2ICjRlSs3g/5esyLxG6w7QH6GHmGRQa6nyJqm3FIt5uxLFixQ7X8QJZosBoQcIEfA0kEY4Zn6v6f/sPSRu+DKIfMvw/OLgnWetgBJqdg5jquHzf0cahnez4VMF5P+gyDAu0qKHqE9bmCqFl0pgbzyYtfUnPmaNgpWPalIC80ydEkEWvphNNu1XO5yv4VclS+Vt0BXjRatR5GKVraKkBauE+GBc3O8aBi55++h6ibgjWFqEJYaIAdsLfC5C3W1ZJJHiMaOGJk0BzmHQmrgnFpjSgR8jG85t6jbM/dUpu0XikFbuCixtYQ4FcLQBWWZMYmrkxxsNvcHojD1kPz0/zkFiI2kmYWeM7tZZ0jpVUk/xHLTiX8UehzlnsaCb259nqt2S6T1Vhgqm3U=
    - secure: YI9tF/pC1kFRkUmIuzUVHdho8DkhlVvyC2qh1WRDIMTI6wht+iD+Bq8mh+tFnbQDSORr7wqsJ96f4wpUmugIHwmSNbhX7fRduN+Q7bNQ0DBA0VzGE9QF7BjKc4jRAjAQwK58UfSWpGm4IrxKXfc8H/t2HaLFkGirRL/s0Q00YXBfoZgFMi+BwQmT+C83/I7JtMr9Z+26wBsO4S4XJPyGBFcc4nnyENc4brrivTUE1R/XHMAmrwjE8Aa6ZrUhZpWGXyXI0tTYkyBjA7TyiTaIsKYjrf12PlxaSV2xA38pBRelyZ8fZPjWAnr3rdSgKoJzWY12YtEwPZaJJVM48RwsWLSXppnYjztF21bNB8VvsIuvqAsSc0xbb+4Su1Kf/qrokCBXlkFMGQor31sIR1f7J6RW8Tx6NzQHvz19wDMD0yrHNI3tNrXj4YLZU2sgcwXZj7OKFOenZCDsTXHtVKkCZg3NBeZ2Mwga5gLbt/0IlNjKYBaMgPx6jmcMoDN1WZAYuvdowd7OoEsSMkh/4/BesQXSXhqw0kctY3Il2q8rAHuXmeWxD/AF6j5eRA6IUP467HRuxdNP/cwSbZA+5x6NxbTKXH586ziY7IvV+/rKJbk81TTeYV6EKX/uCKwixv63QEiH+1sUQ8T+NdicQWb+eAYeID8LaUA96UjRIkN21pg=
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - docker_images
before_install:
  - docker load -i docker_images/images.tar || true
before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)
install:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install
script:
  - yarn tf:init
  - yarn tf:apply
  - yarn build
deploy:
  provider: s3
  bucket: andrew.molyuk.com
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  local-dir: build
  skip_cleanup: true
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master' || travis_terminate 1
